# Generated by Django 3.1.4 on 2021-01-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=155)),
                ('brand_icon', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=155)),
                ('category_icon', models.ImageField(upload_to='images/')),
                ('category_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('city_name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('div_name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('size', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(null=True)),
                ('land_size', models.IntegerField(blank=True, null=True)),
                ('house_size', models.IntegerField(blank=True, null=True)),
                ('baths', models.IntegerField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('_type', models.CharField(blank=True, choices=[('BIRD', 'bird'), ('LIVESTOCK', 'livestock'), ('PETS', 'pets')], max_length=155, null=True)),
                ('condition', models.CharField(blank=True, choices=[('USED', 'USED'), ('NEW', 'new')], max_length=155, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.category')),
            ],
        ),
    ]
