# Generated by Django 3.1.4 on 2021-01-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='_type',
            field=models.CharField(blank=True, choices=[('BIRD', 'bird'), ('LIVESTOCK', 'livestock'), ('PETS', 'pets'), ('Water Purifier', 'water purifier'), ('SOFAS', 'sofas'), ('BEDS', 'beds'), ('TABLES', 'tables')], max_length=155, null=True),
        ),
    ]
